### PR TITLE
media-sound/forked-daapd:  Add new ebuild

### PR DESCRIPTION
**Pull request by erikmack**
An issue with this ebuild is that it depends on mxml which is in currently only in the science overlay.  Will query out-of-band how to handle this (presumably by asking the maintainer to submit mxml to the official tree).

### CODE REVIEW

**Comment by alunduil** [comment]
If you're not generating the Changelog with echangelog or repoman, just drop it.

**Comment by alunduil** [comment]
Indent ``*DEPEND`` with tabs.  See any other ebuild in this repository for an example.

**Comment by alunduil** [comment]
Not required, but I like to alphabetize my dependences.

**Comment by alunduil** [comment]
Be consistent with your closing quotes (dangling vs inline).

**Comment by alunduil** [comment]
If I recall correctly, there should be an eautoreconf, why didn't you use it?

**Comment by alunduil** [comment]
Does the ``daapd`` user need to exist before compilation?  Usually new users are added in install.

**Comment by alunduil** [comment]
I'd place a newline after the emake install invocation.

**Comment by alunduil** [comment]
Again, go ahead and copy ``app-emulation/docker`` for the metadata updates.

**Comment by alunduil** [comment]
Also, ensure the travis output is passing or it won't be merged.  Free repoman check for you.

**Comment by erikmack** [comment]
> If I recall correctly, there should be an eautoreconf

You would think.  It's not [documented](https://devmanual.gentoo.org/function-reference/build-functions/index.html).  I also tried it (both eautoreconf and eautoconf) in case they were simply undocumented, but the build failed.

> Does the daapd user need to exist before compilation? Usually new users are added in install.

The [manual](https://devmanual.gentoo.org/ebuild-writing/users-and-groups/index.html) says "Regardless of whether you are adding a group or a user, this should be performed in the pkg_setup function"

The Travis build will continue to fail until I can get mxml into the tree.

Your other comments have been addressed and the ebuild is otherwise ready for review.

**Comment by alunduil** [comment]
eautoreconf is a part of autotools eclass.  I'd recommend giving the eclasses a perusal even though they're not technically part of the quizzes they can be invaluable as I'm sure you're finding.

From that manual page you linked: "You may also use the pkg_preinst or pkg_postinst functions for user creation, if the user is not required during or before src_install."  I always prefer to do things that configure the system as late as possible (more style).  You can choose to leave it or move it.  Let's keep knocking on the repoman failures and see what happens.  Otherwise, looking great.

**Comment by erikmack** [comment]
> eautoreconf is a part of autotools eclass. I'd recommend giving the eclasses a perusal

Very good, will review this weekend.

> Does the daapd user need to exist before compilation?

> You may also use the pkg_preinst or pkg_postinst functions for user creation

It turns out that by calling fowners in src_install, that makes pkg_preinst/pkg_postinst too late to add the user.  I could move user creation and fowners to pkg_preinst but it seems like fowners should die early in the sandbox if needed.  So, I moved user creation back to pkg_setup.  Do you agree that's justified?

**Comment by alunduil** [comment]
Yep, just wanted to make sure you had thought about it and I could understand why that decision was being made.  The dependent package should be in the overlay now.  Want to re-run the travis test and see if we can get this pull request green?

**Comment by erikmack** [comment]
Important: Please don't commit mxml to the official tree!
Egg on my face:  all this effort to get mxml in the tree, and today I see that it's in the tree already, just with a different name (dev-libs/mini-xml).  I like to think that it wasn't there when I first started this ebuild in February-ish, then I'd have an excuse for missing that detail.
Anyway, this guy should be ready for review/merging, but please remove mxml from the overlay.

**Pull request merged**
