### PR TITLE
Add lxd ebuild

### PR DESCRIPTION
**Pull request by erikmack**
Thanks for reviewing this.

### CODE REVIEW

**Comment by alunduil** [comment]
Your init file and service file use different default options.  Did you want them to have parity?

**Comment by alunduil** [comment]
Can you cite where you found to do linguas the way you did?  I would've expected simply a LINGUAS variable per https://devmanual.gentoo.org/general-concepts/linguas/index.html.

**Comment by alunduil** [comment]
``*DEPEND`` should be tab indented.  See any of my ebuilds for an example.

**Comment by alunduil** [comment]
Why do you move ``${S}``?

**Comment by alunduil** [comment]
Punt testing by leaving your test function as what you expect and set ``RESTRICT=test`` above the function along with your comment on testing not working.

**Comment by alunduil** [comment]
systemd units are installed unconditionally.  Drop the systemd USE flag.

**Comment by alunduil** [comment]
Why not depend on bridge utils and ensure that the default setup simply works rather than trying to inform users?

**Comment by alunduil** [comment]
I would say only include the latest version in this pull request.  If we miss a version we can add it due to a bug later.  My policy is also to only keep three versions with any given set of KEYWORDs.

**Comment by alunduil** [comment]
Go ahead and list yourself first in the metadata and see ``app-emulation/docker`` for an example of metadata for a proxy-maintained package.

**Comment by alunduil** [comment]
Otherwise, looking very good.  Sorry for a large number of comments rather than one.

**Comment by erikmack** [comment]
> Can you cite where you found to do linguas the way you did? I would've expected simply a LINGUAS variable per https://devmanual.gentoo.org/general-concepts/linguas/index.html.

LINGUAS is for emerge-time, but all ebuilds have to add linguas_* to IUSE by some technique (see sys-apps/man-pages).  LINGUAS in an ebuild is ignored (I tried it).

> Why do you move ${S}?

After unpacking the archive, I move it from ${WORKDIR}/${P} to ${WORKDIR}/src/${P} so that 'go build' sees that its under the goofy /{src,bin,pkg} hierarchy that go imposes.  What makes it extra goofy is that 'go build' immediately downloads a second copy of the package.  Next time around I'll try wedging it into williamh's golang-build.eclass.

Your other comments should all be addressed in 0.13.

Also, I added the slot operator to dev-lang/go that williamh was asking in IRC today for you to add to all your go ebuilds.

**Comment by alunduil** [comment]
Alright, how about using the l10n eclass for LINGUAS?  go build immediately downloading a second copy doesn't cause a sandbox violation?  Interesting.  How hard would it be to retrofit the golang-build eclass into the ebuild?

**Comment by alunduil** [comment]
I would also drop 0.11 and 0.12 and squash everything into an add version 0.13 commit.

**Comment by erikmack** [comment]
> Alright, how about using the l10n eclass for LINGUAS?

Good call, done.

> How hard would it be to retrofit the golang-build eclass into the ebuild?

I'm an hour into it, and it might work.  Will know more tomorrow.

> I would also drop 0.11 and 0.12 and squash everything into an add version 0.13 commit.

Done

**Comment by alunduil** [comment]
Awesome.  Let me know when you're ready for another review.

**Comment by erikmack** [comment]
I think this is ready for your expert eyes.  It fully uses golang-build.eclass now, and is generally cleaner with less directory goofy.

**Comment by alunduil** [comment]
EGO_PN is a golang-build variable, right?  Just for my own edification.

Is the lxd group required for compilation?  Would it be better to move it to a later phase?  See [1]

Your unpack may be correct but looks very strange.  Especially since it calls tar itself and uses go get (I would've expected that in a fetch phase).  Let me know why unpack is unusable for this purpose.  See [2]

Why the line continuation on line 63?  

Rather than using sed to apply patches, I highly recommend using patch (yes even for seemingly trivial things).  The reason for this is that sed won't cause build failure if it fails to apply during a bump but a patch will.  Thus, if someone decides to help out and bump your package the patch will stop silly breakages.

The bash-completion should be processed by the template processor not just copied.  Alternatively use newbashcomp instead of dobashcomp in install.

My rule of thumb on tests is that we run the ones that will verify our environment is correct that can run in the ebuild environment.  The rest are part of upstream's quality process.  Thus, you can drop the comments about some tests not running if you'd like.

Looks like a proper ebuild though.  Keep in mind that most of these are me learning go ebuilds and not necessarily requirements for changes.

--
[1] https://devmanual.gentoo.org/ebuild-writing/functions/src_unpack/index.html
[2] https://devmanual.gentoo.org/ebuild-writing/users-and-groups/index.html

**Comment by erikmack** [comment]
> EGO_PN is a golang-build variable, right? Just for my own edification.

Correct, it's the single required var for golang-build

> Is the lxd group required for compilation? Would it be better to move it to a later phase? See [1]

Moved.

> Your unpack may be correct but looks very strange. Especially since it calls tar itself ... Let me know why unpack is unusable for this purpose ... Why the line continuation on line 63?

That was a copy-paste from go-tools-9999/go-net-9999.  I've replaced the direct tar call (which was used in those other ebuilds for the "--strip-components 1" switch) with safer operations.

> ... and uses go get (I would've expected that in a fetch phase) ...

So, this may be a thing to fix.  There's been a lot of discussion on the list [1], which never seemed to resolve.  The safest and simplest of the discussed alternatives is to tar up the output of 'go get' into a single archive, mirror it, and that becomes SRC_URI.  Would you be okay with that?

[1] https://archives.gentoo.org/gentoo-dev/message/d41cbe16eefb877d888157334944d0f6

> Rather than using sed to apply patches, I highly recommend using patch (yes even for seemingly trivial things). The reason for this is that sed won't cause build failure if it fails to apply during a bump but a patch will. Thus, if someone decides to help out and bump your package the patch will stop silly breakages.

It's a patch now.  Your explanation makes perfect sense (fail early and loudly).

> The bash-completion should be processed by the template processor not just copied. Alternatively use newbashcomp instead of dobashcomp in install.

I went with newbashcomp to just rename it.  While lxc.in suggests templating, there isn't actually any template processing that happens.

> My rule of thumb on tests is that we run the ones that will verify our environment is correct that can run in the ebuild environment. The rest are part of upstream's quality process. Thus, you can drop the comments about some tests not running if you'd like.

Makes sense, done.

**Comment by erikmack** [comment]
>> ... and uses go get (I would've expected that in a fetch phase) ...

> So, this may be a thing to fix. There's been a lot of discussion on the list [1], which never seemed to resolve. The safest and simplest of the discussed alternatives is to tar up the output of 'go get' into a single archive, mirror it, and that becomes SRC_URI. Would you be okay with that?

> [1] https://archives.gentoo.org/gentoo-dev/message/d41cbe16eefb877d888157334944d0f6

So, I've followed through on this.  I've factored out the 'go get' by running it at ebuild-author time.  In other words, I become upstream because go embeds its dependency information in go-only code rather than in a universally-accessible markup.  Kind of a shame about go...

Anyway, this is ready for review again.  Thanks!

**Comment by alunduil** [comment]
That makes the SRC_URI look super strange but I'm sure we'll re-visit this in the future.  Did the conversation about ``go get`` ever resolve?  I almost wish we didn't need any go packages as it's extremely strange to package.  Merging but keep your eye on how to handle the go deps.

**Pull request merged**
